sudo: required

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output *.adoc
  - ls
  - cd $TRAVIS_BUILD_DIR/output && ls && zip conf.zip *.pdf

after_error:
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-pdf

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: /documents/output/conf.zip
  skip_cleanup: true
